global:
  message: welcome to order-service!
server:
  port: 8083
  message: hello from dev environment!
spring:
  datasoource:
    url: jdbc:h2:mem:orderdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

