spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:order_master
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
